import jsPDF from 'jspdf'
import autoTable from 'jspdf-autotable'

// --- Types --------------------------------------------------------------------
declare module 'jspdf' {
  interface jsPDF {
    lastAutoTable: { finalY: number }
  }
}

export interface TaskExportData {
  title: string
  status: string
  priority: string
  assignee: string
  created_at: string
  completed_at?: string
}

export interface StatsExportData {
  total: number
  completed: number
  pending: number
  rate: string
}

const COLORS = {
  cyan: [6, 182, 212] as [number, number, number],
  dark: [2, 6, 23] as [number, number, number],
  slate: [100, 116, 139] as [number, number, number],
  border: [226, 232, 240] as [number, number, number],
}

// --- Internal Helpers ---------------------------------------------------------

/** Calculates human-readable duration between two ISO strings */
function calculateDuration(start: string, end?: string): string {
  if (!end) return '--'
  const diff = new Date(end).getTime() - new Date(start).getTime()
  if (diff < 0) return '0h'

  const hours = Math.floor(diff / (1000 * 60 * 60))
  const days = Math.floor(hours / 24)

  if (days > 0) return `${days}d ${hours % 24}h`
  return `${hours}h`
}

/** Generates a Pie Chart for Status and Bar Chart for Priorities */
async function generateCharts(tasks: TaskExportData[], stats: StatsExportData) {
  const canvas = document.createElement('canvas')
  canvas.width = 800
  canvas.height = 400
  const ctx = canvas.getContext('2d')!

  // 1. Draw Pie Chart (Status)
  const centerX = 200, centerY = 200, radius = 150
  const data = [stats.completed, stats.pending]
  const colors = ['#06b6d4', '#0f172a']
  let startAngle = 0

  data.forEach((val, i) => {
    const slice = (Math.PI * 2 * val) / stats.total
    ctx.fillStyle = colors[i]
    ctx.beginPath()
    ctx.moveTo(centerX, centerY)
    ctx.arc(centerX, centerY, radius, startAngle, startAngle + slice)
    ctx.closePath()
    ctx.fill()
    startAngle += slice
  })

  // 2. Draw Simple Bar Chart (Priorities)
  const priorities = ['high', 'medium', 'low']
  const counts = priorities.map(p => tasks.filter(t => t.priority.toLowerCase() === p).length)
  const max = Math.max(...counts, 1)

  ctx.fillStyle = '#0f172a'
  ctx.font = 'bold 24px Helvetica'
  ctx.fillText('PRIORITY LOAD', 450, 50)

  priorities.forEach((label, i) => {
    const barW = (counts[i] / max) * 300
    ctx.fillStyle = '#06b6d4'
    ctx.fillRect(450, 80 + (i * 100), barW, 40)
    ctx.fillStyle = '#64748b'
    ctx.font = '20px Helvetica'
    ctx.fillText(`${label.toUpperCase()} (${counts[i]})`, 450, 75 + (i * 100))
  })

  return canvas.toDataURL('image/png')
}

// --- Main Export Function -----------------------------------------------------

export async function exportAdvancedReport(
  tasks: TaskExportData[],
  stats: StatsExportData,
  userName?: string,
  dateRange?: string
) {
  const doc = new jsPDF('p', 'mm', 'a4')
  const pageWidth = doc.internal.pageSize.getWidth()
  const now = new Date()

  // Header
  doc.setFillColor(...COLORS.cyan)
  doc.rect(0, 0, pageWidth, 45, 'F')
  doc.setTextColor(255, 255, 255)
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(22)
  doc.text('DEVHUB PERFORMANCE AUDIT', 20, 25)

  doc.setFontSize(9)
  doc.setFont('helvetica', 'normal')
  doc.text(`GENERATED BY: ${userName?.toUpperCase() || 'SYSTEM'}`, 20, 35)
  doc.text(`PERIOD: ${dateRange || now.toLocaleDateString()}`, pageWidth - 20, 35, { align: 'right' })

  // Visuals Section
  doc.setTextColor(...COLORS.dark)
  doc.setFontSize(14)
  doc.text('EXECUTIVE OVERVIEW', 20, 60)

  const chartImg = await generateCharts(tasks, stats)
  doc.addImage(chartImg, 'PNG', 20, 70, 170, 85)

  // Legend for Pie Chart
  doc.setFontSize(8)
  doc.setFillColor('#06b6d4').rect(20, 160, 3, 3, 'F')
  doc.text(`Completed (${stats.completed})`, 25, 163)
  doc.setFillColor('#0f172a').rect(55, 160, 3, 3, 'F')
  doc.text(`Pending (${stats.pending})`, 60, 163)

  // Task Table
  doc.setFontSize(14)
  doc.setFont('helvetica', 'bold')
  doc.text('MISSION LEDGER & VELOCITY', 20, 180)

  autoTable(doc, {
    startY: 185,
    head: [['OBJECTIVE', 'PRIORITY', 'CREATED', 'COMPLETED', 'DURATION']],
    body: tasks.map(t => [
      t.title.toUpperCase(),
      t.priority.toUpperCase(),
      t.created_at.split('T')[0],
      t.completed_at?.split('T')[0] || '--',
      calculateDuration(t.created_at, t.completed_at)
    ]),
    theme: 'striped',
    headStyles: { fillColor: COLORS.dark, fontSize: 9 },
    columnStyles: {
      0: { cellWidth: 60 },
      4: { fontStyle: 'bold', textColor: COLORS.cyan }
    },
    styles: { fontSize: 8, cellPadding: 4 }
  })

  // Footer
  const pageCount = doc.getNumberOfPages()
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i)
    doc.setFontSize(7)
    doc.setTextColor(...COLORS.slate)
    doc.text(`CONFIDENTIAL // PAGE ${i} OF ${pageCount}`, pageWidth / 2, 285, { align: 'center' })
  }

  const dateStr = now.toISOString().split('T')[0]
  const cleanName = userName ? userName.toLowerCase().replace(/[^a-z0-9]/g, '_') : 'system'
  const fileName = `${cleanName}_performance_report_${dateStr}.pdf`

  console.log(`[CRYPTO-PDF] Dispatching Advanced Report: ${fileName}`)
  
  const pdfBlob = doc.output('blob')
  const url = URL.createObjectURL(pdfBlob)
  const link = document.createElement('a')
  link.href = url
  link.download = fileName
  document.body.appendChild(link)
  link.click()
  document.body.removeChild(link)
  URL.revokeObjectURL(url)
  
  console.log('[CRYPTO-PDF] Success. Report transmitted to browser terminal.')

}